In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import  ColumnTransformer
from sklearn.metrics import r2_score, log_loss

from sklearn.neighbors import KNeighborsRegressor

import os
os.chdir(r"D:\Machine_Learning_CDAC-AI\a] Datasets") #fetch the dataset from the folder

## Boston Data

In [4]:
boston = pd.read_csv("Boston.csv")
X = boston.drop('medv',axis=1)
y=boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [5]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'score'])
df_scores.sort_values('score', ascending=False)

   Ks     score
3   4  0.588671
2   3  0.559148
4   5  0.556344
5   6  0.515386
1   2  0.513579
6   7  0.496433
7   8  0.491477
8   9  0.479582
9  10  0.448195
0   1  0.293025

### With Standard Sclaing

In [6]:
scaler = StandardScaler().set_output(transform="pandas")

In [7]:
scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

In [8]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

   Ks  R2 score
4   5  0.720809
3   4  0.720349
1   2  0.720333
8   9  0.708297
5   6  0.705555
2   3  0.704720
7   8  0.701514
6   7  0.701001
9  10  0.698105
0   1  0.691733

## MinMax

In [9]:
scaler = MinMaxScaler().set_output(transform="pandas")

In [10]:
scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

In [11]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

   Ks  R2 score
2   3  0.713301
3   4  0.711778
4   5  0.704968
1   2  0.692504
5   6  0.677821
0   1  0.675963
6   7  0.655112
7   8  0.639558
8   9  0.633555
9  10  0.627269

# Housing Dataset

In [12]:
housing = pd.read_csv('Housing.csv')
housing

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [13]:
X = housing.drop('price',axis=1)
y=housing['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=26)

In [14]:
from sklearn.compose import make_column_selector

ohe=OneHotEncoder(sparse_output=False,drop="first").set_output(transform="pandas")

trans = ColumnTransformer(
    transformers=[("OHE", ohe, make_column_selector(dtype_include=object))], remainder="passthrough",
    verbose_feature_names_out=False).set_output(transform="pandas")

X_trn_ohe = trans.fit_transform(X_train)
X_tst_ohe = trans.transform(X_test)

In [15]:
Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_ohe, y_train)
    y_pred = knn.predict(X_tst_ohe)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'score'])
df_scores.sort_values('score', ascending=False)

    Ks     score
12  13  0.412618
11  12  0.405094
13  14  0.404482
14  15  0.397812
10  11  0.380636
8    9  0.380597
9   10  0.380562
7    8  0.355538
6    7  0.344230
5    6  0.324026
3    4  0.316453
4    5  0.302245
2    3  0.276467
1    2  0.247089
0    1 -0.112122

### Standard Scale

In [16]:
scaler = StandardScaler().set_output(transform="pandas")

In [17]:
scaler.fit(X_trn_ohe)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_trn_ohe)  # Actual transformation of data
X_tst_scl = scaler.transform(X_tst_ohe)

In [18]:
Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
14  15  0.592741
6    7  0.582084
7    8  0.578456
5    6  0.573699
8    9  0.572106
13  14  0.571086
12  13  0.563442
11  12  0.562764
10  11  0.562593
9   10  0.555870
4    5  0.543642
3    4  0.502649
2    3  0.444069
1    2  0.347386
0    1  0.127980

### MinMax Scaler

In [19]:
scaler = MinMaxScaler().set_output(transform="pandas")

In [20]:
scaler.fit(X_trn_ohe)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_trn_ohe)  # Actual transformation of data
X_tst_scl = scaler.transform(X_tst_ohe)

In [21]:
Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
14  15  0.535478
10  11  0.522093
13  14  0.518775
11  12  0.515236
12  13  0.514149
9   10  0.513080
8    9  0.498411
7    8  0.485104
6    7  0.472166
5    6  0.421053
4    5  0.380489
2    3  0.367814
3    4  0.345036
1    2  0.264879
0    1  0.061186

# Concrete Strength

In [27]:
conc = pd.read_csv("Concrete_Data.csv")
X, y = conc.drop('Strength', axis=1), conc['Strength']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state=26)

In [28]:
Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
3    4  0.686443
4    5  0.677831
2    3  0.670443
5    6  0.664499
6    7  0.655339
7    8  0.654481
8    9  0.653360
9   10  0.650433
10  11  0.644905
11  12  0.638284
12  13  0.630390
13  14  0.617334
0    1  0.600760
14  15  0.597252
1    2  0.585665

In [29]:
# Standard Scaler
scaler = StandardScaler().set_output(transform="pandas")

scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
4    5  0.709663
7    8  0.698523
5    6  0.695438
6    7  0.692776
2    3  0.692301
8    9  0.691397
3    4  0.687542
9   10  0.684710
10  11  0.679353
11  12  0.669135
13  14  0.653043
12  13  0.652452
1    2  0.649537
14  15  0.641319
0    1  0.618293

In [30]:
# MinMax Scaler
scaler = MinMaxScaler().set_output(transform="pandas")

scaler.fit(X_train)   # Means and SD get calculated
X_trn_scl = scaler.transform(X_train)  # Actual transformation of data
X_tst_scl = scaler.transform(X_test)

Ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
scores=[]
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, r2_score(y_test, y_pred)])
df_scores = pd.DataFrame(scores, columns=['Ks', 'R2 score'])
df_scores.sort_values('R2 score', ascending=False)

    Ks  R2 score
5    6  0.686453
6    7  0.681397
4    5  0.678191
7    8  0.677849
8    9  0.674605
9   10  0.671331
2    3  0.661415
10  11  0.658691
3    4  0.654668
11  12  0.652885
12  13  0.636796
13  14  0.625914
14  15  0.611317
1    2  0.594986
0    1  0.565138